[package]
name = "euler-solutions"
version = "0.1.0"
authors = ["will <will@wrign.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "3.0.0", features = ["derive"] }
