[package]
name = "euler-solutions"
version = "0.0.0"
authors = ["will <william@rigney.com.au>"]
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dev-dependencies]
# snapshot testing
insta = "1.10.0"

[dependencies]
# terminal colours
colored = "2.0.0"
# argument parsing
clap = { version = "3.0.0", features = ["derive"] }
