[package]
name = "euler-solutions"
version = "0.0.0"
authors = ["will <william@rigney.com.au>"]
edition = "2018"

[dependencies]
# terminal colours
ansi_term = "0.12.1"
# argument parsing
clap = { version = "3.0.0", features = ["derive"] }
