name: Run problems

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: cargo run --release -- -ct > run.txt
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: upload-run
        path: run.txt
